### ISSUE TITLE
[Feature] Command-line (CLI) support

### ISSUE THREAD

**Issue by mahimairaja** [capjamesg/visionscript#1]
Using the libraries like `click` the program could be accessed from command line : 

```diff
- python3 lang.py --file ./your_file.vic
+ vscript your_file.vlc
```

Advantage : 
So that the program could be executed anywhere on the computer.  And lang.py need not be in the same directory all time.

And does the project is accepting any PR?

**Comment by capjamesg** [comment]
I was just trying to get this to work, but was going to use `pipx`. `click` feels like a better way to go! Feel free to submit a PR for using `click` for the CLI!

**Comment by mahimairaja** [comment]
Glad to hear from you. Hope to submit my pull request ASAP.

**Comment by capjamesg** [comment]
Please make sure you pull the latest version of the code. I have made a lot of changes!

**Comment by mahimairaja** [comment]
I am getting a parsing error in the latest code, trying to debug it : 
```bash
    raise UnexpectedEOF(expected_terminals, state=frozenset(i.s for i in to_scan))
lark.exceptions.UnexpectedEOF: Unexpected end-of-input. Expected one of: 
        * EOF
        * EOL
```

Meanwhile, I just made a small [cli version](https://github.com/mahimairaja/vscript) of the vision script. Do check it out!

**Comment by capjamesg** [comment]
Would you mind submitting your CLI version as a PR against the repository? Then, your contribution will become an official part of the language! With regard to the exception, can you share what code you were trying to execute?

**Comment by mahimairaja** [comment]
I just resolved the bug and just noticed the emerging features of the updated project. It's fantastic! Just love to work further in the project with newer ideas!

**Comment by capjamesg** [comment]
Are you still up for submitting the PR? If not, I can add the click stuff too! I'd love to get this working soon so I can start sharing this more widely!

**Comment by mahimairaja** [comment]
Yes, I am submitting the PR! It's cooking!

**Comment by capjamesg** [comment]
I am closing this since we now have a fully-featured CLI. If you have more suggestions on what we can add, feel free to open up a new Issue!
